#!/bin/bash
#
cd /home/paredes/pheno/testnn/pheno_study/analysis/neuralnet
source /cvmfs/sft.cern.ch/lcg/views/LCG_94python3/x86_64-slc6-gcc8-opt/setup.sh
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_20_to_200_2b2j.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_20_to_200_2b2j.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_200_to_500_2b2j.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_200_to_500_2b2j.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_500_to_1000_2b2j.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_500_to_1000_2b2j.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_1000_to_infty_2b2j.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_1000_to_infty_2b2j.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_20_to_200_4b.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_20_to_200_4b.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_200_to_500_4b.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_200_to_500_4b.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_500_to_1000_4b.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_500_to_1000_4b.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_1000_to_infty_4b.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_ptj1_1000_to_infty_4b.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_0.5_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_0.5_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_10.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_10.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_1.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_1.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_20.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_20.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_2.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_2.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_3.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_3.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_5.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_5.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_7.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_7.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m0.5_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m0.5_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m10.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m10.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m1.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m1.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m20.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m20.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m2.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m2.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m5.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m5.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m7.0_merged.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_4b_highstats_signal_hh_TopYuk_1.0_SlfCoup_m7.0_merged.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_bbh.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_bbh.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_bbh.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_bbh.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.5_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.8_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_0.9_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.8.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.8.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.8.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_0.8.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.2.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.2.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.2.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.2.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_15.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_15.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_15.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_15.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_1.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_4.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_4.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_4.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_4.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_6.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_6.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_6.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_6.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_8.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_8.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_8.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_8.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_9.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_9.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_9.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_9.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m15.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m15.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m15.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m15.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m1.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m4.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m4.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m4.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m4.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m6.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m6.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m6.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m6.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m8.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m8.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m8.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m8.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m9.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m9.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m9.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.0_SlfCoup_m9.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.1_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.2_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m0.5.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m0.5.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m0.5.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m0.5.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m10.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m10.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m10.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m10.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m1.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m1.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m1.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m1.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m20.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m20.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m20.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m20.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m2.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m2.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m2.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m2.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m3.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m3.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m3.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m3.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m5.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m5.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m5.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m5.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m7.0.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m7.0.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m7.0.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_signal_hh_TopYuk_1.5_SlfCoup_m7.0.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbar.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbar.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbb.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbb.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbb.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_ttbb.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_tth.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_tth.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_tth.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_tth.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_wh.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_wh.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_wh.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_wh.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zh.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zh.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zh.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zh.ro.boosted_3.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zz.ro.boosted_0.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zz.ro.boosted_1.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zz.ro.boosted_2.root
python appendNtuple_boosted_ObO.py -i /data/atlas/atlasdata/DiHiggsPheno/ntuples/150719/new_split_ntuples/loose_noGenFilt_zz.ro.boosted_3.root
